# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='io',
            name='problem',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='problems.Problem'),
            preserve_default=False,
        ),
    ]
