# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_io_problem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IO',
            new_name='Test',
        ),
    ]
