# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_auto_20151204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='init_memory',
            field=models.CharField(help_text="Separate by a space. Use '*' to represent empty spots.", max_length=200, verbose_name='Initial Memory'),
        ),
    ]
